// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9MBuamVkks1oIUpR6DEDPRiEiY-OO21A',
    appId: '1:387180656913:web:f8c0495dc3e570d964b4b0',
    messagingSenderId: '387180656913',
    projectId: 'componentes-8002c',
    authDomain: 'componentes-8002c.firebaseapp.com',
    storageBucket: 'componentes-8002c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKAxUYCy5NozezJaSwSHi5lryyfuCS2r0',
    appId: '1:387180656913:android:a2d920638514635d64b4b0',
    messagingSenderId: '387180656913',
    projectId: 'componentes-8002c',
    storageBucket: 'componentes-8002c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRqgaqnPGLglnLpKB5YAZKm4XOsIvPcuc',
    appId: '1:387180656913:ios:b2b8310a9c65d8a364b4b0',
    messagingSenderId: '387180656913',
    projectId: 'componentes-8002c',
    storageBucket: 'componentes-8002c.appspot.com',
    iosBundleId: 'com.example.pract3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRqgaqnPGLglnLpKB5YAZKm4XOsIvPcuc',
    appId: '1:387180656913:ios:b51047281ac9552464b4b0',
    messagingSenderId: '387180656913',
    projectId: 'componentes-8002c',
    storageBucket: 'componentes-8002c.appspot.com',
    iosBundleId: 'com.example.pract3.RunnerTests',
  );
}
